#!/bin/bash

REPO="wearesolutionarchitects/mysteryland"

# Labels: name | color | description
labels=(
    "abwaerts                   | 6f42c1 | Kategorie für die Band Abwärts"
    "ac_dc                      | 6f42c1 | Kategorie für die Band AC/DC"
    "amphitheater               | 0e8a16 | Veranstaltungsorte in einem Amphitheater"
    "arena_oberhausen           | 0e8a16 | Veranstaltungsorte in der Arena Oberhausen"
    "bryan_adams                | 6f42c1 | Kategorie für den Künstler Bryan Adams"
    "die_aerzte                 | 1d76db | Kategorie für die Band die ärzte - aus Berlin"
    "artist                     | fbca04 | Künstler:innen und Bands im Fokus der Galerie"
    "bela_b                     | 6f42c1 | Kategorie für den Künstler Bela B"
    "billy_idol                 | 6f42c1 | Kategorie für den Künstler Billy Idol"
    "bochum                     | 0e8a16 | Veranstaltungsorte in Bochum"
    "brings                     | 6f42c1 | Kategorie für die Band Brings"
    "broilers                   | 6f42c1 | Kategorie für die Band Broilers"
    "campino                    | 6f42c1 | Kategorie für den Künstler Campino"
    "the_cure                   | 6f42c1 | Kategorie für die Band The Cure"
    "depeche_mode               | 1d76db | Kategorie für die Band Depeche Mode"
    "deutschland                | 0e8a16 | Veranstaltungsorte in Deutschland"
    "die_beatsteaks             | 6f42c1 | Kategorie für die Band Die Beatsteaks"
    "die_toten_hosen            | 6f42c1 | Kategorie für die Band Die Toten Hosen"
    "dortmund                   | 0e8a16 | Veranstaltungsorte in Dortmund"
    "duesseldorf                | 0e8a16 | Veranstaltungsorte in Düsseldorf"
    "duran_duran                | 6f42c1 | Kategorie für die Band Duran Duran"
    "event                      | f9d0c4 | Inhalte & Metadaten zu Konzerten und Festivals"
    "extrabreit                 | 6f42c1 | Kategorie für die Band Extrabreit"
    "fanta_4                    | 6f42c1 | Kategorie für die Band Die Fantastischen Vier"
    "farin_urlaub               | 6f42c1 | Kategorie für den Künstler Farin Urlaub"
    "frankfurt                  | 0e8a16 | Veranstaltungsorte in Frankfurt am Main"
    "festival                   | 6f42c1 | Kategorie für Festivals und Großveranstaltungen"
    "festhalle                  | 0e8a16 | Veranstaltungen in der Festhalle Frankfurt"
    "flughafen_halle_401        | 0e8a16 | Veranstaltungen im Flughafen Halle 401"
    "furt                       | 6f42c1 | Kategorie für die Band FURT (Farin Urlaub Racing Team)"
    "fury_in_the_slaughterhouse | 6f42c1 | Kategorie für die Band Fury in the Slaughterhouse"
    "foto                       | 006b75 | Bildinhalt oder fotografische Besonderheiten"
    "dave_gahan                 | 6f42c1 | Kategorie für den Künstler Dave Gahan"
    "genesis                    | 6f42c1 | Kategorie für die Band Genesis"
    "gelsenkirchen              | 0e8a16 | Veranstaltungsorte in Gelsenkirchen"
    "groenemeyer                | 6f42c1 | Kategorie für den Künstler Herbert Grönemeyer"
    "guano_apes                 | 6f42c1 | Kategorie für die Band Guano Apes"
    "hamburg                    | 0e8a16 | Veranstaltungsorte in Hamburg"
    "holly_johnson              | 6f42c1 | Kategorie für den Künstler Holly Johnson"
    "jahr                       | cfd3d7 | Jahr der Veranstaltung für chronologische Filter"
    "lenny_kravitz              | 6f42c1 | Kategorie für den Künstler Lenny Kravitz"
    "markthalle                 | 0e8a16 | Veranstaltungen in der Markthalle Hamburg"
    "metallica                  | 6f42c1 | Kategorie für die Band Metallica"
    "memento                    | 5319e7 | Erinnerungen oder persönliche Highlights"
    "oberhausen                 | 0e8a16 | Veranstaltungsorte in Oberhausen"
    "oomph                      | 6f42c1 | Kategorie für die Band Oomph!"
    "nena                       | 6f42c1 | Kategorie für die Künstlerin Nena"
    "nackt_unter_kannibalen     | 6f42c1 | Kategorie für die Band Nackt unter Kannibalen"
    "night_of_the_proms         | 6f42c1 | Kategorie für die Veranstaltung Night of the Proms"
    "peter_maffay               | 6f42c1 | Kategorie für den Künstler Peter Maffay"
    "preis                      | ff9f1c | Preisangabe in € für das Event"
    "omd                        | 6f42c1 | Kategorie für die Band OMD (Orchestral Manoeuvres in the Dark)"
    "rammstein                  | 6f42c1 | Kategorie für die Band Rammstein"
    "simple_minds               | 6f42c1 | Kategorie für die Band Simple Minds"
    "sondaschule                | 6f42c1 | Kategorie für die Band Sondaschule"
    "stadt                      | 0e8a16 | Veranstaltungsorte nach Stadt sortiert"
    "sylt                       | 0e8a16 | Veranstaltungen auf Sylt"
    "ticket                     | d73a4a | Das Ticket für den Event oder das Festival"
    "tor_3                      | 6f42c1 | Veranstaltungen im Tor 3 in Düsseldorf"
    "tour                       | b60205 | Tournee oder Festival-Zugehörigkeit"
    "u2                         | 6f42c1 | Kategorie für die Band U2"
    "udo_lindenberg             | 6f42c1 | Kategorie für den Künstler Udo Lindenberg"
    "unheilig                   | 6f42c1 | Kategorie für den Künstler Unheilig (der Graf)"
    "venue                      | 0366d6 | Detaillierte Informationen zur Event-Location"
    "westerland                 | 0e8a16 | Veranstaltungen in Westerland auf Sylt"
    "westfalenhalle             | 0e8a16 | Veranstaltungen in der Westfalenhalle Dortmund"
    "westfalenhalle_2           | 0e8a16 | Veranstaltungen in der Westfalenhalle 2 Dortmund"
    "we_will_rock_you           | 6f42c1 | Kategorie für das Musical We Will Rock You"
    "xanten                     | 0e8a16 | Veranstaltungsorte in Xanten"
)

# Erstelle Labels via GitHub CLI
for label in "${labels[@]}"; do
  IFS='|' read -r name color desc <<< "$label"
  color=$(echo "$color" | tr -d '[:space:]')
  name=$(echo "$name" | xargs)
  desc=$(echo "$desc" | xargs)
  echo "▶️ Erstelle Label: $name"
  echo "➡️  Name: '$name' | Color: '$color' | Desc: '$desc'"
  gh label create "$name" --repo "$REPO" --color "$color" --description "$desc"
done