#!/bin/bash

REPO="wearesolutionarchitects/mysteryland"

# Labels: name | color | description
labels=(
    "1live                      | 6f42c1 | Kategorie für den Radiosender & Konzertveranstalter 1LIVE"
    "abwaerts                   | 6f42c1 | Kategorie für die Band Abwärts"
    "ac_dc                      | 6f42c1 | Kategorie für die Band AC/DC"
    "amphitheater               | 0e8a16 | Veranstaltungsorte in einem Amphitheater"
    "arena_oberhausen           | 0e8a16 | Veranstaltungsorte in der Arena Oberhausen"
    "bryan_adams                | 6f42c1 | Kategorie für den Künstler Bryan Adams"
    "die_aerzte                 | 1d76db | Kategorie für die Band die ärzte - aus Berlin"
    "artist                     | fbca04 | Künstler:innen und Bands im Fokus der Galerie"
    "bela_b                     | 6f42c1 | Kategorie für den Künstler Bela B"
    "berlin                     | 0e8a16 | Veranstaltungsorte in Berlin"
    "bielefeld                  | 0e8a16 | Veranstaltungsorte in Bielefeld"
    "billy_idol                 | 6f42c1 | Kategorie für den Künstler Billy Idol"
    "bochum                     | 0e8a16 | Veranstaltungsorte in Bochum"
    "brigitte_nielsen           | 6f42c1 | Kategorie für die Künstlerin Brigitte Nielsen"
    "brings                     | 6f42c1 | Kategorie für die Band Brings"
    "broilers                   | 6f42c1 | Kategorie für die Band Broilers"
    "campino                    | 6f42c1 | Kategorie für den Künstler Campino"
    "concert_team_duesseldorf   | 6f42c1 | Kategorie für das Konzertteam Düsseldorf"
    "the_cure                   | 6f42c1 | Kategorie für die Band The Cure"
    "dancin_machine             | 6f42c1 | Kategorie für die Band Dancin' Machine"
    "dbe_koeln                  | 6f42c1 | Kategorie für das Konzertteam DBE Köln"
    "depeche_mode               | 1d76db | Kategorie für die Band Depeche Mode"
    "deutschland                | 0e8a16 | Veranstaltungsorte in Deutschland"
    "die_beatsteaks             | 6f42c1 | Kategorie für die Band Die Beatsteaks"
    "die_toten_hosen            | 6f42c1 | Kategorie für die Band Die Toten Hosen"
    "dortmund                   | 0e8a16 | Veranstaltungsorte in Dortmund"
    "duesseldorf                | 0e8a16 | Veranstaltungsorte in Düsseldorf"
    "duran_duran                | 6f42c1 | Kategorie für die Band Duran Duran"
    "e_werk                     | 0e8a16 | Veranstaltungen im E-Werk"
    "erasure                    | 6f42c1 | Kategorie für die Band Erasure"
    "essen                      | 0e8a16 | Veranstaltungsorte in Essen"
    "event                      | f9d0c4 | Inhalte & Metadaten zu Konzerten und Festivals"
    "exilia                     | 6f42c1 | Kategorie für die Band Exilia"
    "extrabreit                 | 6f42c1 | Kategorie für die Band Extrabreit"
    "fanta_4                    | 6f42c1 | Kategorie für die Band Die Fantastischen Vier"
    "farin_urlaub               | 6f42c1 | Kategorie für den Künstler Farin Urlaub"
    "frankfurt                  | 0e8a16 | Veranstaltungsorte in Frankfurt am Main"
    "festival                   | 6f42c1 | Kategorie für Festivals und Großveranstaltungen"
    "festhalle                  | 0e8a16 | Veranstaltungen in der Festhalle Frankfurt"
    "flughafen_halle_401        | 0e8a16 | Veranstaltungen im Flughafen Halle 401"
    "flughafen_tempelhof        | 0e8a16 | Veranstaltungen im Flughafen Tempelhof"
    "furt                       | 6f42c1 | Kategorie für die Band FURT (Farin Urlaub Racing Team)"
    "fury_in_the_slaughterhouse | 6f42c1 | Kategorie für die Band Fury in the Slaughterhouse"
    "foto                       | 006b75 | Bildinhalt oder fotografische Besonderheiten"
    "dave_gahan                 | 6f42c1 | Kategorie für den Künstler Dave Gahan"
    "genesis                    | 6f42c1 | Kategorie für die Band Genesis"
    "gelsenkirchen              | 0e8a16 | Veranstaltungsorte in Gelsenkirchen"
    "glueckaufkampfbahn         | 0e8a16 | Veranstaltungen auf der Glückaufkampfbahn"
    "groenemeyer                | 6f42c1 | Kategorie für den Künstler Herbert Grönemeyer"
    "guano_apes                 | 6f42c1 | Kategorie für die Band Guano Apes"
    "hagen                      | 0e8a16 | Veranstaltungsorte in Hagen"
    "hamburg                    | 0e8a16 | Veranstaltungsorte in Hamburg"
    "handwerker_promotion       | 6f42c1 | Kategorie für die Konzertagentur Handwerker-Promotion"
    "holly_johnson              | 6f42c1 | Kategorie für den Künstler Holly Johnson"
    "iss_dome                   | 0e8a16 | Veranstaltungen im ISS Dome in Düsseldorf"
    "jahr                       | cfd3d7 | Jahr der Veranstaltung für chronologische Filter"
    "koeln                      | 0e8a16 | Veranstaltungsorte in Köln"
    "koenig_pilsener_arena      | 0e8a16 | Veranstaltungen in der König-Pilsener-Arena"
    "konzert                    | 6f42c1 | Kategorie für Konzerte und Live-Auftritte"
    "kkt                        | 6f42c1 | Kategorie für die Konzertagentur KKT"
    "kool_and_the_gang          | 6f42c1 | Kategorie für die Band Kool & The Gang"
    "krefeld                    | 0e8a16 | Veranstaltungsorte in Krefeld"
    "kulturfabrik               | 0e8a16 | Veranstaltungen in der Kulturfabrik"
    "kulturzentrum_pelmke       | 0e8a16 | Veranstaltungen im Kulturzentrum PELMKE"
    "land                       | 0e8a16 | Veranstaltungsorte nach Land sortiert"
    "lanxess_arena              | 0e8a16 | Veranstaltungen in der Lanxess Arena Köln"
    "laternen_joe               | 6f42c1 | Kategorie für die Band Laternen-Joe (die ärzte)"
    "lenny_kravitz              | 6f42c1 | Kategorie für den Künstler Lenny Kravitz"
    "lido                       | 0e8a16 | Veranstaltungen im Lido"
    "loft_concerts              | 6f42c1 | Kategorie für die Konzertagentur Loft Concerts"
    "ltu_arena                  | 0e8a16 | Veranstaltungen in der LTU arena"
    "mama_concerts              | 6f42c1 | Kategorie für die Konzertagentur Mama Concerts"
    "markthalle                 | 0e8a16 | Veranstaltungen in der Markthalle Hamburg"
    "mercedes_benz_arena        | 0e8a16 | Veranstaltungen in der Mercedes-Benz Arena"
    "merkur_spiel_arena         | 0e8a16 | Veranstaltungen in der Merkur Spiel-Arena"
    "milli_vanilli              | 6f42c1 | Kategorie für die Band Milli Vanilli"
    "mitsubishi_electric_halle  | 0e8a16 | Veranstaltungen in der Mitsubishi Electric Halle"
    "metallica                  | 6f42c1 | Kategorie für die Band Metallica"
    "memento                    | 5319e7 | Erinnerungen oder persönliche Highlights"
    "muengersdorfer_stadion     | 0e8a16 | Veranstaltungen im Müngersdorfer Stadion"
    "musical_dome               | 0e8a16 | Veranstaltungen im Musical Dome Köln"
    "musikzirkus                | 0e8a16 | Veranstaltungen im Musikzirkus"
    "nena                       | 6f42c1 | Kategorie für die Künstlerin Nena"
    "nackt_unter_kannibalen     | 6f42c1 | Kategorie für die Band Nackt unter Kannibalen"
    "night_of_the_proms         | 6f42c1 | Kategorie für die Veranstaltung Night of the Proms"
    "oberhausen                 | 0e8a16 | Veranstaltungsorte in Oberhausen"
    "olympiastadion             | 0e8a16 | Veranstaltungen im Olympiastadion Berlin"
    "oomph                      | 6f42c1 | Kategorie für die Band Oomph!"
    "osterholz_scharmbeck       | 0e8a16 | Veranstaltungsorte in Osterholz-Scharmbeck"
    "palladium                  | 0e8a16 | Veranstaltungen im Palladium"
    "pc_69                      | 0e8a16 | Veranstaltungen im PC 69"
    "perrish_toppano            | 6f42c1 | Kategorie für die Band Perrish & Toppano"
    "peter_maffay               | 6f42c1 | Kategorie für den Künstler Peter Maffay"
    "peters_pop_show            | 6f42c1 | Kategorie für die Peters Pop Show"
    "philipshalle               | 0e8a16 | Veranstaltungen in der Philipshalle"
    "preis                      | ff9f1c | Preisangabe in € für das Event"
    "prime_entertainment        | 6f42c1 | Kategorie für die Konzertagentur Prime Entertainment"
    "omd                        | 6f42c1 | Kategorie für die Band OMD (Orchestral Manoeuvres in the Dark)"
    "rammstein                  | 6f42c1 | Kategorie für die Band Rammstein"
    "rhein_energie_stadion      | 0e8a16 | Veranstaltungen im RheinEnergieStadion"
    "robbie_zieger              | 6f42c1 | Kategorie für den Künstler & Erfinder Robbie Zieger"
    "simple_minds               | 6f42c1 | Kategorie für die Band Simple Minds"
    "slipknot                   | 6f42c1 | Kategorie für die Band Slipknot"
    "sondaschule                | 6f42c1 | Kategorie für die Band Sondaschule"
    "so_36                      | 0e8a16 | Veranstaltungen im SO36"
    "sporthalle                 | 0e8a16 | Veranstaltungen in der Sporthalle"
    "stadt                      | 0e8a16 | Veranstaltungsorte nach Stadt sortiert"
    "stadthalle                 | 0e8a16 | Veranstaltungen in der Stadthalle"
    "stadtpark                  | 0e8a16 | Veranstaltungen im Stadtpark"
    "sylt                       | 0e8a16 | Veranstaltungen auf Sylt"
    "tanzbrunnen                | 0e8a16 | Veranstaltungen im Tanzbrunnen Köln"
    "ticket                     | d73a4a | Das Ticket für den Event oder das Festival"
    "tor_3                      | 6f42c1 | Veranstaltungen im Tor 3 in Düsseldorf"
    "tour                       | b60205 | Tournee oder Festival-Zugehörigkeit"
    "turbinenhalle              | 0e8a16 | Veranstaltungen in der Turbinenhalle"
    "u2                         | 6f42c1 | Kategorie für die Band U2"
    "udo_lindenberg             | 6f42c1 | Kategorie für den Künstler Udo Lindenberg"
    "unheilig                   | 6f42c1 | Kategorie für den Künstler Unheilig (der Graf)"
    "unna                       | 0e8a16 | Veranstaltungsorte in Unna"
    "veltins_arena              | 0e8a16 | Veranstaltungen in der Veltins-Arena"
    "venue                      | 0366d6 | Detaillierte Informationen zur Event-Location"
    "wilhelmsplatz              | 0e8a16 | Veranstaltungen am Wilhelmsplatz"
    "witten                     | 0e8a16 | Veranstaltungsorte in Witten"
    "werk_stadt                 | 0e8a16 | Veranstaltungen in der Werk*stadt"
    "westerland                 | 0e8a16 | Veranstaltungen in Westerland auf Sylt"
    "westfalenhalle             | 0e8a16 | Veranstaltungen in der Westfalenhalle Dortmund"
    "westfalenhalle_2           | 0e8a16 | Veranstaltungen in der Westfalenhalle 2 Dortmund"
    "westfalenhalle_4           | 0e8a16 | Veranstaltungen in der Westfalenhalle 4 Dortmund"
    "westfalenpark              | 0e8a16 | Veranstaltungen im Westfalenpark Dortmund"
    "we_will_rock_you           | 6f42c1 | Kategorie für das Musical We Will Rock You"
    "wulheide                   | 0e8a16 | Veranstaltungen in der Wulheide"
    "xanten                     | 0e8a16 | Veranstaltungsorte in Xanten"
    "zeche_carl                 | 0e8a16 | Veranstaltungen in der Zeche Carl"
    "zdf                        | 6f42c1 | Kategorie für den Veranstalter ZDF (Zweites Deutsches Fernsehen)"
)

# Erstelle Labels via GitHub CLI
for label in "${labels[@]}"; do
  IFS='|' read -r name color desc <<< "$label"
  color=$(echo "$color" | tr -d '[:space:]')
  name=$(echo "$name" | xargs)
  desc=$(echo "$desc" | xargs)
  echo "▶️ Erstelle Label: $name"
  echo "➡️  Name: '$name' | Color: '$color' | Desc: '$desc'"
  gh label create "$name" --repo "$REPO" --color "$color" --description "$desc"
done