

name: 📅 Neues Event erfassen
description: Erstelle einen neuen Event-Eintrag für mysteryland.biz
title: "YYYY-MM-DD – Künstler:in@Ort/Location"
labels: [event]
assignees:
  - hfanieng
body:
  - type: input
    id: event_date
    attributes:
      label: 📆 Datum des Events
      description: Verwende das Format JJJJ-MM-TT
      placeholder: 1979-09-29
    validations:
      required: true

  - type: input
    id: artist
    attributes:
      label: 🎤 Künstler:in
      description: Wer tritt auf?
      placeholder: Extrabreit
    validations:
      required: true

  - type: input
    id: city
    attributes:
      label: 🏙️ Stadt
      placeholder: Hagen
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: 📍 Location / Veranstaltungsort
      placeholder: Wilhelmsplatz
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Beschreibung
      description: Optionaler Freitext zum Event
      placeholder: Beschreibung, besondere Eindrücke, etc.

  - type: input
    id: tags
    attributes:
      label: 🏷️ Tags
      description: Kommagetrennte Schlagworte für Labels und Auswertung
      placeholder: deutschland, festival, extrabreit

  - type: checkboxes
    id: files
    attributes:
      label: 📎 Medien vorhanden?
      description: Gibt es bereits Medien (Fotos, Tickets etc.)?
      options:
        - label: Ja, als Datei vorhanden
        - label: Ja, wird nachgereicht
        - label: Nein