name: ✨ Feature Request
description: Vorschlag für neue Funktionen oder Verbesserungen
title: "[Feature] "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Danke für deinen Feature-Vorschlag! Bitte beantworte die folgenden Fragen so konkret wie möglich.

  - type: input
    id: titel
    attributes:
      label: Kurzer Titel
      placeholder: Z. B. „Benutzerprofil bearbeiten“
    validations:
      required: true

  - type: textarea
    id: beschreibung
    attributes:
      label: Beschreibung der Funktion
      description: Was soll die Funktion tun? Wo wird sie gebraucht?
      placeholder: Bitte gib eine konkrete Beschreibung an …
    validations:
      required: true

  - type: textarea
    id: nutzen
    attributes:
      label: Warum ist das nützlich?
      description: Welches Problem wird dadurch gelöst oder welcher Mehrwert entsteht?
    validations:
      required: true

  - type: dropdown
    id: betroffene-bereiche
    attributes:
      label: Betroffene Bereiche
      multiple: true
      options:
        - Frontend
        - Backend
        - Datenbank
        - Dokumentation
        - Tests
        - DevOps

  - type: textarea
    id: hinweise
    attributes:
      label: Weitere Hinweise oder Kontext
      description: Optional – z. B. technische Überlegungen, Links oder Beispiel-PRs