name: 📅 Konzertbericht erfassen
description: Neues Konzert-Event für mysteryland.biz anlegen
title: "YYYY-MM-DD – Künstler:in@Ort/Location"
labels: [event]
assignees:
  - hfanieng
body:
  - type: input
    id: title
    attributes:
      label: 🎤 Künstler:in
      placeholder: Peter Maffay, Die Ärzte, etc.

  - type: input
    id: pubdate
    attributes:
      label: 📅 Datum
      placeholder: "2026-07-17"

  - type: input
    id: city
    attributes:
      label: 📍 Stadt
      placeholder: Köln

  - type: input
    id: venue
    attributes:
      label: 🏟️ Venue
      placeholder: RheinEnergieStadion

  - type: input
    id: price
    attributes:
      label: 💶 Preis
      placeholder: 89.00

  - type: input
    id: asin
    attributes:
      label: 🔗 Amazon ASIN (optional)
      placeholder: B099BYDLLT

  - type: textarea
    id: setlist
    attributes:
      label: 🎶 Setlist
      description: Eine Zeile pro Song (optional)
      placeholder: 01. Liedname

  - type: textarea
    id: review
    attributes:
      label: 📝 Konzertbericht
      placeholder: Eindrücke, Gastauftritte, Atmosphäre, Besonderheiten

  - type: input
    id: tags
    attributes:
      label: 🏷️ Tags
      description: Kommagetrennte Begriffe für Auswertung
      placeholder: deutschland, konzert, köln, 2026

  - type: checkboxes
    id: media
    attributes:
      label: 📎 Medien vorhanden?
      options:
        - label: 🎫 Ticket
        - label: 📷 Fotos
        - label: 🎥 Video