name: Labels

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  synchronize:
    name: Synchronize repository labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: npm
      - name: Synchronize labels
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: npm run script:github:create-labels
